### ISSUE TITLE
The pretrained models from your Google drive are not available.

### ISSUE THREAD

**Issue by indussky8** [ShuoYang-1998/Few_Shot_Distribution_Calibration#10]
Thanks for sharing your code. However, when I unzip the file 'pretrained_model.tar' downloaded from your google drive, it says that the file has been damaged. So, could you please check it?
Best,

**Comment by ShuoYang-1998** [comment]
Hope this can help you.
[https://drive.google.com/file/d/15x4Z1y2KlEbFA8kM427sAEfWw40akFNf/view?usp=sharing](url)
