### ISSUE TITLE
训练策略

### ISSUE THREAD

**Issue by ljjcoder** [ShuoYang-1998/Few_Shot_Distribution_Calibration#13]
感谢您的工作！我有一个问题想请教一下，请问您的pre-train模型是采用rotation方法训练还是采用S2M2_R方法训练？我看save_plk中 默认params.method = 'S2M2_R'，而S2M2_R在S2M2中报告的结果为64.93，并不是您在论文表4中报告的56.37

**Comment by ShuoYang-1998** [comment]
The 56.37 is accuracy when applying LR on the extracted features instead of the finetune strategy in the original paper.
