### ISSUE TITLE
result

### ISSUE THREAD

**Issue by JasemineDing** [ShuoYang-1998/Few_Shot_Distribution_Calibration#14]
Thank you for your work
After running evaluate_DC.py, I found that the accuracy on 5W-5S is only 83. Could you please tell me why? My parameters are the trained parameters you sent .
Thanks.

**Comment by ShuoYang-1998** [comment]
Which dataset？

**Comment by JasemineDing** [comment]
Thank you for your reply.

I was running on CUB's dataset and the previous problem has been solved.
