### ISSUE TITLE
how to measure the similarity between different class variance like table1

### ISSUE THREAD

**Issue by valencebond** [ShuoYang-1998/Few_Shot_Distribution_Calibration#16]
just flatten the covariance matrix and conduct the inner product?

**Comment by ShuoYang-1998** [comment]
Cosine similarly or euclidean distance. Note in Table1 we compute the similarities between variance vectors, not covariance matrices.

**Comment by valencebond** [comment]
thanks for your interpretation, but according to the assumption, features follow the multivariate normal distribution, so there should be a covariance matrix. How to get the variance vector?  the diagonal of the covariance matrix?

**Comment by ShuoYang-1998** [comment]
Correct. The implementation should be np.var
