### ISSUE TITLE
 doesn't continue running

### ISSUE THREAD

**Issue by Yanfei-Qin** [ShuoYang-1998/Few_Shot_Distribution_Calibration#17]
I tested the code on my local machine, which caused by cov matrix is not positive-semidefinite. Anyway, the code doesn't continue running.
![微信截图_20210329100209](https://user-images.githubusercontent.com/72698923/112778564-65e5d080-9077-11eb-99dc-7d26a6f3c148.png)

**Comment by Yanfei-Qin** [comment]
在下载完提取的特征，并调整好文件位置，运行evaluate_DC.py文件，会显示这些警告，卡死之后不会继续运行

**Comment by ShuoYang-1998** [comment]
Maybe you should check your numpy version.

**Comment by Yanfei-Qin** [comment]
Thank you. There's something wrong with my environment

**Comment by ShuoYang-1998** [comment]
You're welcome 😉
