### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by ChenHsing** [ShuoYang-1998/Few_Shot_Distribution_Calibration#18]

**Comment by ChenHsing** [comment]
could you please open source code of Single-View 3D Object Reconstruction from Shape Priors in Memory

**Comment by ShuoYang-1998** [comment]
Thanks for interests. That work is prepared to be extended, and the code will be released upon the journal submission.

**Comment by sunhui-3D** [comment]
Hello, excuse me, I have a problem in the Single-View-3D-Object ,tf_ops/cd/tf_nndistance_so.so is missing. How to solve the problem
