### ISSUE TITLE
How to use Tukey’s Ladder of Powers transformation when the characteristic is negative？

### ISSUE THREAD

**Issue by Yanfei-Qin** [ShuoYang-1998/Few_Shot_Distribution_Calibration#19]
When I use your method, the super parameter of Tukey’s Ladder of Powers is set to 0.5, but the 512 dimensional feature I get through neural network contains negative number (negative number has no even power), so I can't use formula. What should I do?

**Comment by ShuoYang-1998** [comment]
You can attach a ReLU layer after the current network structure to get non-negative features.
