### ISSUE TITLE
您的论文是否和S2M2_R的结果进行了比较

### ISSUE THREAD

**Issue by Qianshaowei** [ShuoYang-1998/Few_Shot_Distribution_Calibration#28]
感谢您的的工作！如题，您的论文是否和S2M2_R的结果进行了比较？如何判断涨点原因是由于S2M2_R的策略和还是您的策略？
感谢回复。

**Comment by ShuoYang-1998** [comment]
请参考论文中的表4，第一行的结果是直接建立在S2M2 feature上的
