### ISSUE TITLE
How many epochs have you trained in tieredImagenet training?

### ISSUE THREAD

**Issue by Dreameo** [ShuoYang-1998/Few_Shot_Distribution_Calibration#29]
What a significant work! I'm very inteasted in your DC work.And I'm just training model in tieredImagenet by WRN+(Classifier loss + Rotation loss),  but I find that the model is difficult to fit and the total loss hardly reduced in several epochs. And I only training the model with one 16GB GPU,batchsize is 20,no test batchsize. So could you please tell me some details about you model training in tieredImagenet? I'm waiting for your reply sincerely. Thanks a lot~

**Comment by Dreameo** [comment]
> What a significant work! I'm very inteasted in your DC work.And I'm just training model in tieredImagenet by WRN+(Classifier loss + Rotation loss), but I find that the model is difficult to fit and the total loss hardly reduced in several epochs. And I only training the model with one 16GB GPU,batchsize is 20,no test batchsize. So could you please tell me some details about you model training in tieredImagenet? I'm waiting for your reply sincerely. Thanks a lot~

**Comment by ShuoYang-1998** [comment]
Please refer to S2M2 https://github.com/nupurkmr9/S2M2_fewshot for training details.
