### ISSUE TITLE
Problem with Reproducing the TieredImagenet Results

### ISSUE THREAD

**Issue by ehsansaleh** [ShuoYang-1998/Few_Shot_Distribution_Calibration#30]
Hi there,

First of all, thanks for your interesting work. I hope you're having a warm and enjoyable summer down in Australia (it's kind of getting really cold here)!

We followed your advice in #29, #21, and #1 to reproduce the tiered-imagenet; we have taken the pre-trained models out of https://github.com/nupurkmr9/S2M2_fewshot and used your `save_plk.py` script to generate the features from the `WideResNet28_10_S2M2_R` backbone. We had to introduce a slight modification to your code on Line 81 of `save_plk.py` to include the tiered-Imagenet dataset:

```
if params.dataset == 'miniImagenet' or params.dataset == 'CUB' or params.dataset == 'tieredImagenet':
        datamgr       = SimpleDataManager(84, batch_size = 256)
```

We're having a problem reproducing the tiered-imagenet (i.e., 78.19 ± 0.25% and 89.90 ± 0.41% for the 5W1S and 5W5S, respectively):

* For the 5-ways, 1-shot case on tiered-imagenet, we are getting 74.58 ± 0.22 % after 10000 runs.
* For the 5-ways, 5-shot case on tiered-imagenet, we are getting 88.20 ± 0.14 % after 10000 runs.

However, on mini-imagenet, your paper's results (i.e., 68.57 ± 0.55% and 82.88 ± 0.42% for the 5W1S and 5W5S, respectively) are more in line with what our code is producing:

* For the 5-ways, 1-shot case on mini-imagenet, we are getting 67.9 ± 0.21% after 10000 runs.
* For the 5-ways, 5-shot case on mini-imagenet, we are getting 83.02 ± 0.14% after 10000 runs.

We're trying to identify what's causing this mismatch on tieredImagenet, and we completely understand that you had to add these results during the rebuttals period. 

1. Since the code you used to produce the tiered-imagenet results may have a few different lines from the main branch, would you please consider pushing those changes to a branch on this repo? If you're on a tight schedule, just attaching a zip file with python scripts would be certainly fine (we can take care of `diff`ing things, and trying to figure out the mystery).
2. Did you also use the same 84 pixels size for the pre-backbone transformation on the tiered -imagenet data? I'm asking since the S2M2R repository is using `image_size=80` for all datasets at https://github.com/nupurkmr9/S2M2_fewshot/blob/master/save_features.py#L63
3. Would you please consider sharing the tiered-imagenet features on your google drive even if for only few days? This would be enormously helpful to us, since if the features are present, we won't even have to dig into what may have been different when generating the features.
4. Could you please report your `scikit-learn`'s full version? We're only asking since `scikit-learn` isn't exactly "stable" with respect to its default hyper-parameters.

The 750-sample calibrated experiments are somewhat expensive and we're on a tight schedule with rebuttals. We would really appreciate it if you could get back to us as soon as possible. Looking forward to hearing from you!

Sincerely, Ehsan

**Comment by llg123123** [comment]
Hello, can you send me the features you extracted from the tiered miniimagenet dataset? Or give a download link. I've been doing research in this field recently to verify the effect of DC model. Thank you very much.

**Comment by llg123123** [comment]
> Hi there,
> 
> First of all, thanks for your interesting work. I hope you're having a warm and enjoyable summer down in Australia (it's kind of getting really cold here)!
> 
> We followed your advice in #29, #21, and #1 to reproduce the tiered-imagenet; we have taken the pre-trained models out of https://github.com/nupurkmr9/S2M2_fewshot and used your `save_plk.py` script to generate the features from the `WideResNet28_10_S2M2_R` backbone. We had to introduce a slight modification to your code on Line 81 of `save_plk.py` to include the tiered-Imagenet dataset:
> 
> ```
> if params.dataset == 'miniImagenet' or params.dataset == 'CUB' or params.dataset == 'tieredImagenet':
>         datamgr       = SimpleDataManager(84, batch_size = 256)
> ```
> 
> We're having a problem reproducing the tiered-imagenet (i.e., 78.19 ± 0.25% and 89.90 ± 0.41% for the 5W1S and 5W5S, respectively):
> 
> * For the 5-ways, 1-shot case on tiered-imagenet, we are getting 74.58 ± 0.22 % after 10000 runs.
> * For the 5-ways, 5-shot case on tiered-imagenet, we are getting 88.20 ± 0.14 % after 10000 runs.
> 
> However, on mini-imagenet, your paper's results (i.e., 68.57 ± 0.55% and 82.88 ± 0.42% for the 5W1S and 5W5S, respectively) are more in line with what our code is producing:
> 
> * For the 5-ways, 1-shot case on mini-imagenet, we are getting 67.9 ± 0.21% after 10000 runs.
> * For the 5-ways, 5-shot case on mini-imagenet, we are getting 83.02 ± 0.14% after 10000 runs.
> 
> We're trying to identify what's causing this mismatch on tieredImagenet, and we completely understand that you had to add these results during the rebuttals period.
> 
> 1. Since the code you used to produce the tiered-imagenet results may have a few different lines from the main branch, would you please consider pushing those changes to a branch on this repo? If you're on a tight schedule, just attaching a zip file with python scripts would be certainly fine (we can take care of `diff`ing things, and trying to figure out the mystery).
> 2. Did you also use the same 84 pixels size for the pre-backbone transformation on the tiered -imagenet data? I'm asking since the S2M2R repository is using `image_size=80` for all datasets at https://github.com/nupurkmr9/S2M2_fewshot/blob/master/save_features.py#L63
> 3. Would you please consider sharing the tiered-imagenet features on your google drive even if for only few days? This would be enormously helpful to us, since if the features are present, we won't even have to dig into what may have been different when generating the features.
> 4. Could you please report your `scikit-learn`'s full version? We're only asking since `scikit-learn` isn't exactly "stable" with respect to its default hyper-parameters.
> 
> The 750-sample calibrated experiments are somewhat expensive and we're on a tight schedule with rebuttals. We would really appreciate it if you could get back to us as soon as possible. Looking forward to hearing from you!
> 
> Sincerely, Ehsan

Hello, I'm lucky to see your comments on this issre, and I also encountered some problems when experimenting on the tiererd Imagenet dataset. I really hope you can help me. 
Can you send me the features obtained from the tiered image data? You can also give me a link. I also want to verify the experimental results of DC method on tiered Imagenet dataset. I followed you on GitHub and saw your research on s2m2 method. But for the tiered Imagenet dataset, I only downloaded it .tar format file, after decompression .pkl format file.  Then I don't know how to get the .jpg format file, can you put the .jpg format file sent to me? Or give me a download link. Or you can tell me what you're right Pkl processing to get JPG.
I really hope you can give me some help or advice. Thanks again!

**Comment by ehsansaleh** [comment]
Hi there llg123123,

First of all, apologies for the late response. 

I'm actively trying to polish the camera-ready code for my repo, and I'll also need to publish a set of large files (like the features, backbone parameters, etc.). I thought I'd be finished with this much earlier and respond to you with a clean set of code/feature files, but the organization turned out to be more time-consuming than I thought. I still need a bit of time before I finish everything and make a major commit to my repo.

Aside from the basic backbones and the S2M2 experiments in my paper, we also added some DC results.  The original DC implementation used the scikit-learn library with a default L-BFGS optimizer. Furthermore, the DC method needed a 640*640 covariance matrix inversion for sampling from a 640-dimensional normal distribution, which was performed using Numpy and ran on the CPU. Moreover, the DC method creates a large number of artificial samples which makes the classifier training much more computationally intensive than what is usual for FSL method. Due to the heavy nature of the DC method, and the fact that it was all performed on the CPU, using the original implementation seemed a bit intractable for our own research. For this, we had to re-implement the DC method from scratch on GPU (i.e., implementing the logistic regressor using L-BFGS, matching the internal hyper-parameters between the the original CPU implementation and scikit-learn and the new GPU implementation, etc.). I'll be releasing our DC GPU code as well once I organize it along with the feature files. I'd be extremely happy if you (or others) find it useful in your own research.

Regarding your specific question, I should say that it brought back some similar (and a bit painful) memories, so I feel for you. However, my memory isn't fresh enough at the moment to respond with confidence.  I'll need sometime to refresh my memory, review what I did, gather my thoughts, and get back to you with a clear and helpful answer. 

I wish I could give you an exact date for my update and getting back you, but I'm hoping it would be within next week. I just wanted to let you know that I'm actively working on prepping the code/files for public use. I'm really sorry that your research hit a road-block and my update isn't ready yet to help with that, but I'm working on it.

Sincerely, Ehsan

**Comment by llg123123** [comment]
> Hi there llg123123,
> 
> First of all, apologies for the late response.
> 
> I'm actively trying to polish the camera-ready code for my repo, and I'll also need to publish a set of large files (like the features, backbone parameters, etc.). I thought I'd be finished with this much earlier and respond to you with a clean set of code/feature files, but the organization turned out to be more time-consuming than I thought. I still need a bit of time before I finish everything and make a major commit to my repo.
> 
> Aside from the basic backbones and the S2M2 experiments in my paper, we also added some DC results. The original DC implementation used the scikit-learn library with a default L-BFGS optimizer. Furthermore, the DC method needed a 640*640 covariance matrix inversion for sampling from a 640-dimensional normal distribution, which was performed using Numpy and ran on the CPU. Moreover, the DC method creates a large number of artificial samples which makes the classifier training much more computationally intensive than what is usual for FSL method. Due to the heavy nature of the DC method, and the fact that it was all performed on the CPU, using the original implementation seemed a bit intractable for our own research. For this, we had to re-implement the DC method from scratch on GPU (i.e., implementing the logistic regressor using L-BFGS, matching the internal hyper-parameters between the the original CPU implementation and scikit-learn and the new GPU implementation, etc.). I'll be releasing our DC GPU code as well once I organize it along with the feature files. I'd be extremely happy if you (or others) find it useful in your own research.
> 
> Regarding your specific question, I should say that it brought back some similar (and a bit painful) memories, so I feel for you. However, my memory isn't fresh enough at the moment to respond with confidence. I'll need sometime to refresh my memory, review what I did, gather my thoughts, and get back to you with a clear and helpful answer.
> 
> I wish I could give you an exact date for my update and getting back you, but I'm hoping it would be within next week. I just wanted to let you know that I'm actively working on prepping the code/files for public use. I'm really sorry that your research hit a road-block and my update isn't ready yet to help with that, but I'm working on it.
> 
> Sincerely, Ehsan

Thank you very much for your reply. I look forward to your early completion of the work, thank you！

**Comment by ehsansaleh** [comment]
> > Hi there llg123123,
> > First of all, apologies for the late response.
> > I'm actively trying to polish the camera-ready code for my repo, and I'll also need to publish a set of large files (like the features, backbone parameters, etc.). I thought I'd be finished with this much earlier and respond to you with a clean set of code/feature files, but the organization turned out to be more time-consuming than I thought. I still need a bit of time before I finish everything and make a major commit to my repo.
> > Aside from the basic backbones and the S2M2 experiments in my paper, we also added some DC results. The original DC implementation used the scikit-learn library with a default L-BFGS optimizer. Furthermore, the DC method needed a 640*640 covariance matrix inversion for sampling from a 640-dimensional normal distribution, which was performed using Numpy and ran on the CPU. Moreover, the DC method creates a large number of artificial samples which makes the classifier training much more computationally intensive than what is usual for FSL method. Due to the heavy nature of the DC method, and the fact that it was all performed on the CPU, using the original implementation seemed a bit intractable for our own research. For this, we had to re-implement the DC method from scratch on GPU (i.e., implementing the logistic regressor using L-BFGS, matching the internal hyper-parameters between the the original CPU implementation and scikit-learn and the new GPU implementation, etc.). I'll be releasing our DC GPU code as well once I organize it along with the feature files. I'd be extremely happy if you (or others) find it useful in your own research.
> > Regarding your specific question, I should say that it brought back some similar (and a bit painful) memories, so I feel for you. However, my memory isn't fresh enough at the moment to respond with confidence. I'll need sometime to refresh my memory, review what I did, gather my thoughts, and get back to you with a clear and helpful answer.
> > I wish I could give you an exact date for my update and getting back you, but I'm hoping it would be within next week. I just wanted to let you know that I'm actively working on prepping the code/files for public use. I'm really sorry that your research hit a road-block and my update isn't ready yet to help with that, but I'm working on it.
> > Sincerely, Ehsan
> 
> Thank you very much for your reply. I look forward to your early completion of the work, thank you！

Hi there [llg123123](https://github.com/llg123123),
 
We've just released all the code and data of our paper at [https://github.com/ehsansaleh/firth_bias_reduction](https://github.com/ehsansaleh/firth_bias_reduction), which has 3 sub-repositories:
  1. The S2M2R feature backbone experiments and code are included in the [`code_s2m2rf`](https://github.com/ehsansaleh/code_s2m2rf) repository.
  2. The distribution calibration experiments and code are included in the [`code_dcf`](https://github.com/sabagh1994/code_dcf) repository.
  3. The standard feature backbone experiments are included in the [`code_firth`](https://github.com/ehsansaleh/code_firth) repository.

You may find the [`code_s2m2rf`](https://github.com/ehsansaleh/code_s2m2rf) and [`code_dcf`](https://github.com/sabagh1994/code_dcf) repositories helpful. The `code_s2m2rf` repo has our distribution calibration implementation on cuda, and the `code_s2m2rf` repo is a good starting point for training feature backbones.

We tried to make the setup processes as-user-friendly as possible, and uploaded all sorts of pre-computed features, trained backbone checkpoints, and datasets along with automated downloading shell scripts and step-by-step guides and documentation in the first page of each repository. 

Feel free to check our work out, and let us know if you had any questions or issues. We'll try to be as helpful as possible.

Sincerely, Ehsan

**Comment by llg123123** [comment]
> 
Firstly, thanks for your reply.Your work is wonderful. It will be of great help to my future research. Thank you very much
